services:
  db:
    image: mysql:9.2
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: petclinic
      MYSQL_USER: petclinic
      MYSQL_PASSWORD: petclinic
    ports:
      - "3306:3306"  # Changed to avoid conflict
      - "33060:33060"
    volumes:
      - mysql-db-1:/var/lib/mysql  # Fixed syntax
    networks:
      - net1
  petclinic:
    image: mostafaabdelazziz/petclinic
    environment:
      - SPRING_PROFILES_ACTIVE=mysql
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/petclinic
      - SPRING_DATASOURCE_USERNAME=petclinic
      - SPRING_DATASOURCE_PASSWORD=petclinic
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_JPA_SHOW_SQL=true
    ports:
      - "8888:8080"
    networks:
      - net1
    depends_on:
      - db